name: Deploy Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, welearn-fe]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build frontend
        run: npm run build
      - name: Deploy build
        run: |
          rm -rf /home/ec2-user/welearn/app/WeLearn-Frontend/build
          cd /home/ec2-user/welearn/runners/frontend/_work/WeLearn-Frontend/WeLearn-Frontend
          cp -r build /home/ec2-user/welearn/app/WeLearn-Frontend/